### ISSUE TITLE
Change directory and listing directory will not work

### ISSUE THREAD

**Issue by viradex** [arnavt78/bubbleos#1]
Whenever I try to enter the following in the Bubble shell, it won't work.

This is what my directory looks like (simplified):

```
bubble D:\ $ ls
Some Folder
```

When I try to `cd` into that, it throws an error.

```
bubble D:\ $ cd Some Folder
Some does not exist.
```

I think this is because Bubble doesn't understand the space. Is there a fix for this?

**Comment by arnavthorat78** [comment]
Hi, thanks for leaving an issue. This issue has been fixed in our latest commit.
